"""
main.py
-------
FastAPI backend for the Legal AI platform. Ties together all Week 1-3
modules behind a REST API that the Streamlit frontend (or anything else)
can call.

Endpoints:
    POST /upload          -> upload a PDF, runs extraction + chunking + embedding
    GET  /summary/{doc_id} -> plain-language summary of the uploaded document
    GET  /clauses/{doc_id} -> classified clauses (payment/confidentiality/liability/termination)
    GET  /risks/{doc_id}   -> flagged risky terms with explanations
    POST /chat             -> ask a question about a specific uploaded document

Run with:
    uvicorn main:app --reload
Then open http://127.0.0.1:8000/docs for interactive API docs (auto-generated by FastAPI).
"""

import os
import shutil
import uuid

from fastapi import FastAPI, UploadFile, File, HTTPException
from pydantic import BaseModel

from pdf_extractor import extract_text_from_pdf, extract_full_text
from chunker import chunk_text
from vector_store import VectorStore
from summarizer import Summarizer
from clause_classifier import ClauseClassifier
from risk_detector import detect_risks
from qa_chatbot import LegalChatbot

app = FastAPI(title="Legal AI API")

UPLOAD_DIR = "./data/uploads"
os.makedirs(UPLOAD_DIR, exist_ok=True)

# In-memory store of processed documents, keyed by doc_id.
# For a student project this is fine; a production system would use a
# real database instead of a Python dict that resets on server restart.
DOCUMENTS = {}

# Heavy models are loaded once at startup, not per-request — loading
# them per-request would be extremely slow (each load takes seconds).
print("Initializing models — this may take a minute on first run...")
vector_store = VectorStore()
summarizer = Summarizer()
clause_classifier = ClauseClassifier()
chatbot = LegalChatbot(vector_store=vector_store)
print("All models loaded. API ready.")


class ChatRequest(BaseModel):
    doc_id: str
    question: str


@app.post("/upload")
async def upload_document(file: UploadFile = File(...)):
    """Upload a PDF and run the full ingestion pipeline on it."""
    if not file.filename.endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are supported.")

    doc_id = str(uuid.uuid4())[:8]
    save_path = os.path.join(UPLOAD_DIR, f"{doc_id}.pdf")

    with open(save_path, "wb") as f:
        shutil.copyfileobj(file.file, f)

    pages = extract_text_from_pdf(save_path)
    if not pages:
        raise HTTPException(status_code=400, detail="Could not extract any text from this PDF.")

    chunks = chunk_text(pages, chunk_size=150, overlap=30)
    vector_store.add_chunks(chunks, doc_name=doc_id)

    full_text = extract_full_text(save_path)

    DOCUMENTS[doc_id] = {
        "filename": file.filename,
        "path": save_path,
        "pages": pages,
        "chunks": chunks,
        "full_text": full_text,
    }

    return {
        "doc_id": doc_id,
        "filename": file.filename,
        "num_pages": len(pages),
        "num_chunks": len(chunks),
        "message": "Document processed successfully. Use doc_id for other endpoints.",
    }


@app.get("/summary/{doc_id}")
def get_summary(doc_id: str):
    """Return a plain-language summary of the uploaded document."""
    doc = _get_document_or_404(doc_id)
    summary = summarizer.summarize_document(doc["chunks"])
    return {"doc_id": doc_id, "summary": summary}


@app.get("/clauses/{doc_id}")
def get_clauses(doc_id: str):
    """Return classified clauses grouped by type."""
    doc = _get_document_or_404(doc_id)
    classified = clause_classifier.classify_document(doc["full_text"])
    return {"doc_id": doc_id, "clauses": classified}


@app.get("/risks/{doc_id}")
def get_risks(doc_id: str):
    """Return flagged risky terms with plain-language explanations."""
    doc = _get_document_or_404(doc_id)
    risks = detect_risks(doc["full_text"])
    return {"doc_id": doc_id, "risks": risks}


@app.post("/chat")
def chat(request: ChatRequest):
    """Ask a question about a specific uploaded document (RAG chatbot)."""
    _get_document_or_404(request.doc_id)  # just validate it exists
    result = chatbot.ask(request.question, doc_name=request.doc_id)
    return {"doc_id": request.doc_id, "question": request.question, **result}


def _get_document_or_404(doc_id: str) -> dict:
    if doc_id not in DOCUMENTS:
        raise HTTPException(status_code=404, detail=f"No document found with doc_id '{doc_id}'. Upload it first via /upload.")
    return DOCUMENTS[doc_id]


@app.get("/")
def root():
    return {"message": "Legal AI API is running. See /docs for interactive API documentation."}
